// Generated by https://quicktype.io

export interface LoginResponse {
    token:        string;
    refreshToken: string;
}

// Generated by https://quicktype.io

export interface UserInfoResponse {
    firstName:   string;
    lastName:    string;
    mail:        string;
    direcciones: Direccione[];
    roles:       Role[];
}

export interface Direccione {
    numero:   number;
    calle:    string;
    esquina:  string;
    detalles: string;
    latitud:  string;
    longitud: string;
}

export interface Role {
    role: string;
}


export interface LoginData {
    correo: string,
    contraseña: string
}

export interface NuevoCliente {
    nombre: string;
    apellido: string;
    correo : string;
    password: string;
    direccion: Direccion;
}

export interface Direccion {
    calle: string;
    numero: string;
    esquina: string;
    detalles: string;
    latitud: number;
    longitud: number;
}
