// Generated by https://quicktype.io

export interface LoginResponse {
    token:        string;
    refreshToken: string;
}

// Generated by https://quicktype.io

export interface UserInfoResponse {
    firstName: string;
    lastName:  string;
    roles:     Role[];
}

export interface Role {
    authority: string;
}

export interface LoginData {
    correo: string,
    contraseña: string
}
